export enum ProductCategory {
  CHEMICALS = 'CHEMICALS',
  MACHINES = 'MACHINES',
  TEXTILES = 'TEXTILES',
  MEDICAL = 'MEDICAL',
  HANDICRAFTS = 'HANDICRAFTS',
  FOOD = 'FOOD',
  ELECTRONICS = 'ELECTRONICS',
  AUTOMOTIVE = 'AUTOMOTIVE',
  CONSTRUCTION = 'CONSTRUCTION',
  AGRICULTURE = 'AGRICULTURE',
  OTHER = 'OTHER'
}
